//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacelStory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampOwner
    {
        public long campOwnerId { get; set; }
        public string mobile { get; set; }
        public string username { get; set; }
        public Nullable<bool> gender { get; set; }
        public string type { get; set; }
        public string campCodePrefix { get; set; }
        public string password { get; set; }
    }
}
