//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacelStory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Community
    {
        public long communityId { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string campname { get; set; }
        public string groupName1 { get; set; }
        public string groupName2 { get; set; }
        public string groupName3 { get; set; }
        public string groupName4 { get; set; }
        public string groupName5 { get; set; }
        public string groupName6 { get; set; }
        public string groupName7 { get; set; }
        public string groupName8 { get; set; }
        public string groupName9 { get; set; }
        public string bldNumber { get; set; }
        public string unitNumber { get; set; }
        public string roomNumber { get; set; }
        public string communityHospital { get; set; }
        public string petLicence { get; set; }
        public string communitySaleDepartment { get; set; }
        public string communityService { get; set; }
        public string communityName { get; set; }
        public string kindergarten { get; set; }
        public string communityHospitalPhone { get; set; }
        public string petLicencePhone { get; set; }
        public string communitySaleDepartmentPhone { get; set; }
        public string communityServicePhone1 { get; set; }
        public string communityServicePhone2 { get; set; }
        public string communityPhone { get; set; }
        public string kindergartenPhone { get; set; }
        public string campCode { get; set; }
        public string campOwnerMobile { get; set; }
    }
}
