//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacelStory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PacelDbEntities : DbContext
    {
        public PacelDbEntities()
            : base("name=PacelDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CampOwner> CampOwner { get; set; }
        public DbSet<Community> Community { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Pacel> Pacel { get; set; }
        public DbSet<SignedPacel> SignedPacel { get; set; }
    }
}
