//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacelStory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PacelDbEntities : DbContext
    {
        public PacelDbEntities()
            : base("name=PacelDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CampOwner> CampOwner { get; set; }
        public virtual DbSet<Community> Community { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Pacel> Pacel { get; set; }
        public virtual DbSet<Resend> Resend { get; set; }
        public virtual DbSet<SignedPacel> SignedPacel { get; set; }
    }
}
