//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacelStory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_smsmt_send
    {
        public int Id { get; set; }
        public string account { get; set; }
        public string mobile { get; set; }
        public string content { get; set; }
        public string smsid { get; set; }
        public int priority { get; set; }
        public System.DateTime SubmitTime { get; set; }
    }
}
